[build-system]
# XXX: If your project needs other packages to build properly, add them to this list.
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

[project]
name = "tabascal"
version = "0.0.1"
license = {file = "LICENSE"}
readme = "README.md"
# dynamic = ["version", "readme"]
authors = [
  {name = "Chris Finlay", email = "christopher.finlay@epfl.ch"},
]
maintainers = [
  {name = "Chris Finlay", email = "christopher.finlay@epfl.ch"}
]
description = "Trajectory based Radio Frequency Interference (RFI) subtraction and calibration using Bayesian methods for radio interferometeric data."

requires-python = ">=3.10"
dependencies = [
    "astropy",
    "dask",
    "dask-ms",
    "jax>=0.6.0,<0.10",
    "matplotlib",
    "numpy",
    "numpyro",
    "optax",
    "PyYAML",
    "skyfield",
    "spacetrack",
    "tabsim",
    "tqdm",
    "xarray",
]

[project.optional-dependencies]
ipy = ["ipython", "ipykernel"]
test = ["pytest", "huggingface-hub"]
docs = ["sphinx", "sphinx-rtd-theme"]
cuda12 = ["jax[cuda12]"]
cuda13 = ["jax[cuda13]"]

[project.urls]
Repository = "https://github.com/epfl-radio-astro/tabascal.git"

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
tabascal = "tabascal.scripts.run_tabascal:main"
tab2MS="tabascal.scripts.results_to_MS:main"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "WARNING"
