include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build
  - test
  - perf

variables:
  PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/tabascal:$CI_COMMIT_SHORT_SHA

build_job:
  stage: build
  extends: .container-builder-cscs-gh200
  variables:
    DOCKERFILE: ci/docker/Dockerfile_cuda
    CSCS_REBUILD_POLICY: "if-not-exists"

test_job:
  stage: test
  needs: [build_job]
  extends: .container-runner-daint-gh200
  image: $PERSIST_IMAGE_NAME
  script:
    - . /opt/conda/etc/profile.d/conda.sh
    - conda activate tab
    - cd /tabascal/src
    - python3 -m pytest
  variables:
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1

perf_job:
  stage: perf
  needs: [build_job]
  extends: .container-runner-daint-gh200
  image: $PERSIST_IMAGE_NAME
  script:
    - >
      reframe
      -C $RFM_CONFIG
      -c $RFM_CHECKPATH
      --system=daint:gpu
      --exec-policy=serial
      --run
      --performance-report
  variables:
    RFM_CHECKPATH: ci/reframe/tabascal_perf_check.py
    RFM_CONFIG: ci/reframe/settings.py
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1
  allow_failure: false
