include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build
  - test
  - perf

build_job:
  stage: build
  extends: .container-builder-cscs-gh200
  parallel:
    matrix:
      - JAX_VERSION: ["0.6.0", "latest"]
  variables:
    DOCKERFILE: ci/docker/Dockerfile_cuda
    CSCS_REBUILD_POLICY: "if-not-exists"
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/tabascal:$CI_COMMIT_SHORT_SHA-jax$JAX_VERSION
    DOCKER_BUILD_ARGS: '["JAX_VERSION=$JAX_VERSION"]'

test_job:
  stage: test
  needs: [build_job]
  extends: .container-runner-daint-gh200
  parallel:
    matrix:
      - JAX_VERSION: ["0.6.0", "latest"]
  image: $PERSIST_IMAGE_NAME
  script:
    - . /opt/conda/etc/profile.d/conda.sh
    - conda activate tab
    - cd /tabascal/src
    - python3 -m pytest
  variables:
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/tabascal:$CI_COMMIT_SHORT_SHA-jax$JAX_VERSION

.perf_job_template:
  stage: perf
  needs: [build_job]
  extends: .container-runner-daint-gh200
  image: $PERSIST_IMAGE_NAME
  script:
    - cd /tabascal/src
    - >
      reframe
      -C ci/reframe/settings.py
      -c ci/reframe/tabascal_perf_check.py
      --system=daint:gpu
      --exec-policy=serial
      --run
      --performance-report
      --report-file=reframe_results.json
      -S strict_check=0
    - |
      python ci/reframe/reframe_to_bmf.py reframe_results.json --jax-version "$JAX_VERSION" > bmf_results.json
      bencher run \
        --project tabascal \
        --branch "$CI_COMMIT_REF_NAME" \
        --hash "$CI_COMMIT_SHA" \
        --testbed cscs-daint-gh200 \
        --adapter json \
        --file bmf_results.json
    - |
      if [ "$CRON_RUN" = "true" ]; then
        python ci/reframe/reframe_to_bmf.py reframe_results.json --jax-version "$JAX_VERSION" > bmf_results.json
        bencher run \
          --project tabascal \
          --branch "$CI_COMMIT_REF_NAME" \
          --hash "$CI_COMMIT_SHA" \
          --testbed cscs-daint-gh200 \
          --adapter json \
          --file bmf_results.json
      fi
  variables:
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/tabascal:$CI_COMMIT_SHORT_SHA-jax$JAX_VERSION
    BENCHER_API_TOKEN: $BENCHER_API_TOKEN

# perf_job:
#   extends: .perf_job_template
#   parallel:
#     matrix:
#       - JAX_VERSION: ["0.6.0"]
#   rules:
#     - if: $CRON_RUN != "true"
#

perf_job_cron:
  extends: .perf_job_template
  parallel:
    matrix:
      - JAX_VERSION: ["0.6.0", "latest"]
  rules:
    - if: $CRON_RUN != "true"
    # - if: $CRON_RUN == "true"
    #   allow_failure: true
